//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4332
{
    using System;
    using System.Collections.Generic;
    
    public partial class galyamshin
    {
        public int Id { get; set; }
        public string CodeOrder { get; set; }
        public string CreateDate { get; set; }
        public string CodeClient { get; set; }
        public string Services { get; set; }
        public string ProkatTime { get; set; }
    }
}
